### ISSUE TITLE
Issue with referencing types in files in sub-directories when cwd is at the project root.

### ISSUE THREAD

**Issue by RobRendell** [markusjohnsson/ts-data-checker#4]
I was having difficulty getting ts-data-checker working in a unit test I wanted to write to verify some JSON data files.

My code is in a `factionUtils.test.ts` file that sits next to the file `factionUtils.ts` containing the type I wanted to validate the JSON with, so I created the checker like this, as in your example:

`const {checkJson} = checker('FactionDetails', './factionUtils');`

After multiple attempts and experiments to get it to work, I ended up debugging the failing test into your library code to see what was wrong with my JSON.  It turned out that the validation was failing because Typescript was unable to import the factionUtils.ts file I had referenced.

After trying a few things, I noted that your servicesHost config defined getCurrentDirectory to return `process.cwd()`, and since my test was being run by a test runner with the `cwd` at the top level of the project, I changed my test code to create the checker using a path to the file relative to the project root:

`const {checkJson} = checker('FactionDetails', './src/server/util/factionUtils');`

This got it working, and it was able to validate my JSON data.

It would be nice if ts-data-checker could somehow tell TS to use a cwd that was in the folder containing the call to `checker`, rather than `process.cwd()`.  The only way I can think you could do that would be to take an optional `cwd` parameter in the checker function, to which a user can pass in `__dirname`.  It would be better if there was some way to do it automatically though.

Thanks for the library!

**Comment by markusjohnsson** [comment]
Thank you for your feedback, glad you found the lib useful.

Yes, perhaps an optional parameter with working directory would make sense. I'm also considering if there are other typescript options that needs to be passed to the checker (as in `tsconfig` stuff). Perhaps that would solve this case too, if you could define e.g. the tsconfig paths array.

**Comment by markusjohnsson** [comment]
As a workaround, you could call `process.chdir('./src/server/util')` in your tests, but probably need to change it back at the end of the test…

**Comment by markusjohnsson** [comment]
Just published `ts-data-checker@1.2` where you can do this:

```ts
const { checkValue } = checker("BasicType", "./basic", { workingDir: __dirname });
```

I might consider automatically figuring out working directory relative to the current module using `callsite` or `parent-module` for a future version, but that would be a breaking change.

**Comment by RobRendell** [comment]
Awesome, thanks for the quick turnaround!

Do you think you might add something to the README about this issue?  The Caveats section could note that the path to the file passed to the `checker` function is relative to the cwd of the process, and that you can override that with the `workingDir` optional parameter.

**Comment by markusjohnsson** [comment]
Yeah, added an Options section as well.

**Comment by RobRendell** [comment]
Nice :)
